FROM node:18-alpine AS builder

WORKDIR /app
COPY frontend .
RUN npm install
RUN npm run build

FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/build ./build

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
