-- Drop all TABLE if existss
DROP TABLE if exists hole_results CASCADE;
DROP TABLE if exists hole_scores CASCADE;
DROP TABLE if exists matches CASCADE;
DROP TABLE if exists pairing_players CASCADE;
DROP TABLE if exists pairings CASCADE;
DROP TABLE if exists rounds CASCADE;
DROP TABLE if exists team_members CASCADE;
DROP TABLE if exists teams CASCADE;
DROP TABLE if exists tournaments CASCADE;
DROP TABLE if exists group_members CASCADE;
DROP TABLE if exists groups CASCADE;
DROP TABLE if exists golf_course_holes CASCADE;
DROP TABLE if exists golf_course_tees CASCADE;
DROP TABLE if exists golf_courses CASCADE;
DROP TABLE if exists player_stats CASCADE;
DROP TABLE if exists match_formats CASCADE;
DROP TABLE if exists users CASCADE;